name: FlagsCreatureSpawn
version: 1.0.0-B1
description: Module that adds creature spawn flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: alshain01.FlagsCreatureSpawn.FlagsCreatureSpawn
depend: [Flags]